/* GENERATED by tools/cht_to_c.py - do not edit.
 * source: SCUS-94488_6C4C043E1B0B34C6.cht  sha256 69e31002a21fc7febad2726abd3b34ad55c4c7eed4a47686251dce038f8c1a8e
 * header: Gran Turismo 2 (USA) (Simulation Mode) (Rev 1) [SCUS-94488]
 * Each entry is one database line, verbatim, as (first word, second word). */
#include <stdint.h>
#include "gameshark_vm.h"

/* [True Endurance] - Silent. "Millenium In Rome 2 Hours Endurance" event ends after 2 hours, regardless of how many laps were finished (like in PS2 Gran Turismos). */
static const GsCode gs_true_endurance_codes[] = {
    { 0xA0052A64u, 0x801EF8EFu },  /* A0052A64 801EF8EF # Reset the race overlay for Arcade */
    { 0x80057010u, 0x00000000u },  /* 80057010 0000 */
    { 0xA0052B20u, 0x000000E7u },  /* A0052B20 000000E7 # Reset the race overlay for Simulation */
    { 0x80057010u, 0x00000000u },  /* 80057010 0000 */
    { 0xA4057010u, 0x260201C0u },  /* A4057010 260201C0 */
    { 0xE01D563Bu, 0x000000FFu },  /* E01D563B 00FF */
    { 0xE0046ED5u, 0x00000000u },  /* E0046ED5 0000 */
    { 0x30046ED5u, 0x00000001u },  /* 30046ED5 0001 */
    { 0xE0046ED5u, 0x00000000u },  /* E0046ED5 0000 */
    { 0xA602CE1Cu, 0x00020006u },  /* A602CE1C 00020006 # Restore the max laps counter */
    { 0xC4046ED5u, 0x00000000u },  /* C4046ED5 0000 */
    { 0xA702CE1Cu, 0x00060002u },  /* A702CE1C 00060002 # Turn off the max laps counter */
    { 0xE01D563Bu, 0x00000063u },  /* E01D563B 0063 */
    { 0x301D563Bu, 0x000000FFu },  /* 301D563B 00FF */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
};
static const GsCheat gs_true_endurance = { "True Endurance", gs_true_endurance_codes, sizeof(gs_true_endurance_codes) / sizeof(gs_true_endurance_codes[0]) };

/* [Fixed Event Generator] - Silent. Improves randomly generated events (One-Make races and Event Generator races) by fixing the course generation. */
static const GsCode gs_fixed_event_gen_codes[] = {
    { 0xA40244ECu, 0x800229D8u },  /* A40244EC 800229D8 */
    { 0xA7023037u, 0x6D61616Du },  /* A7023037 6D61616D */
    { 0xA7023039u, 0x53610053u },  /* A7023039 53610053 */
    { 0xA70231ACu, 0x494C6572u },  /* A70231AC 494C6572 */
    { 0xA70231AEu, 0x25535F76u },  /* A70231AE 25535F76 */
    { 0xA70231B0u, 0x3230696Du },  /* A70231B0 3230696D */
    { 0xA70231B2u, 0x0064696Eu },  /* A70231B2 0064696E */
    { 0xA70231B4u, 0x494C0000u },  /* A70231B4 494C0000 */
    { 0xA0050D98u, 0x00000000u },  /* A0050D98 00000000 */
    { 0x90050D98u, 0x800231ACu },  /* 90050D98 800231AC */
    { 0xA0050D9Cu, 0x800231ACu },  /* A0050D9C 800231AC */
    { 0x90050D9Cu, 0x800231B0u },  /* 90050D9C 800231B0 */
    { 0xA0050DA0u, 0x800231B4u },  /* A0050DA0 800231B4 */
    { 0x90050DA0u, 0x00000000u },  /* 90050DA0 00000000 */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
};
static const GsCheat gs_fixed_event_gen = { "Fixed Event Generator", gs_fixed_event_gen_codes, sizeof(gs_fixed_event_gen_codes) / sizeof(gs_fixed_event_gen_codes[0]) };
