/* GENERATED by tools/cht_to_c.py - do not edit.
 * source: SCUS-94455_B421447B10306C8B.cht  sha256 9b614cc38706a8776b9fe1e5247e5ff72753065682110bc0d9ba3c4bd9071745
 * header: Gran Turismo 2 (USA) (Arcade Mode) (Rev 1) [SCUS-94455]
 * Each entry is one database line, verbatim, as (first word, second word). */
#include <stdint.h>
#include "gameshark_vm.h"

/* [Metric units] - Silent.  */
static const GsCode gs_metric_units_codes[] = {
    { 0xA0052A64u, 0x801EF8EFu },  /* A0052A64 801EF8EF # Reset the race overlay for Arcade */
    { 0x80057010u, 0x00000000u },  /* 80057010 0000 */
    { 0xA0052B20u, 0x000000E7u },  /* A0052B20 000000E7 # Reset the race overlay for Simulation */
    { 0x80057010u, 0x00000000u },  /* 80057010 0000 */
    { 0xA71C6A27u, 0x706D6D6Bu },  /* A71C6A27 706D6D6B */
    { 0xA71C6A29u, 0x0068682Fu },  /* A71C6A29 0068682F */
    { 0xA70F853Du, 0x7466006Du },  /* A70F853D 7466006D */
    { 0xA70F8435u, 0x626C676Bu },  /* A70F8435 626C676B */
    { 0xA70F8474u, 0x626C676Bu },  /* A70F8474 626C676B */
    { 0xA70F8476u, 0x662D2F6Du },  /* A70F8476 662D2F6D */
    { 0xA70F8478u, 0x2F746425u },  /* A70F8478 2F746425 */
    { 0xA70F847Au, 0x64257072u },  /* A70F847A 64257072 */
    { 0xA70F847Cu, 0x7072006Du },  /* A70F847C 7072006D */
    { 0xA70F8487u, 0x626C676Bu },  /* A70F8487 626C676B */
    { 0xA70F8489u, 0x662D2F6Du },  /* A70F8489 662D2F6D */
    { 0xA70F848Bu, 0x2F74257Eu },  /* A70F848B 2F74257E */
    { 0xA70F848Du, 0x257E7264u },  /* A70F848D 257E7264 */
    { 0xA70F848Fu, 0x72646D70u },  /* A70F848F 72646D70 */
    { 0xA70F8491u, 0x6D700000u },  /* A70F8491 6D700000 */
    { 0xA70F835Au, 0x626C676Bu },  /* A70F835A 626C676B */
    { 0xA70F835Cu, 0x662D006Du },  /* A70F835C 662D006D */
    { 0xA71C6EA9u, 0x706D6D6Bu },  /* A71C6EA9 706D6D6B */
    { 0xA71C6EABu, 0x0068682Fu },  /* A71C6EAB 0068682F */
    { 0xA71EF476u, 0x626C676Bu },  /* A71EF476 626C676B */
    { 0xA71C2EA7u, 0x626C676Bu },  /* A71C2EA7 626C676B */
    { 0xA71C2EA9u, 0x662D206Du },  /* A71C2EA9 662D206D */
    { 0xA71C2EABu, 0x2074202Fu },  /* A71C2EAB 2074202F */
    { 0xA71C2EADu, 0x202F0000u },  /* A71C2EAD 202F0000 */
    { 0xA403EC6Cu, 0x02602021u },  /* A403EC6C 02602021 */
    { 0xA702F6F4u, 0xB0D8A0C0u },  /* A702F6F4 B0D8A0C0 */
    { 0xA702F6F6u, 0x39233922u },  /* A702F6F6 39233922 */
    { 0xA7030568u, 0x000D0016u },  /* A7030568 000D0016 */
    { 0xA703056Cu, 0xFBDD8000u },  /* A703056C FBDD8000 */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
    { 0xA4020A74u, 0x3084007Fu },  /* A4020A74 3084007F */
    { 0xA7018AC8u, 0x13030000u },  /* A7018AC8 13030000 */
    { 0xA7018ACAu, 0x00090000u },  /* A7018ACA 00090000 */
    { 0xA7018AD0u, 0x30230000u },  /* A7018AD0 30230000 */
    { 0xA7018AD2u, 0x00463446u },  /* A7018AD2 00463446 */
    { 0xA7018C0Cu, 0x17C30000u },  /* A7018C0C 17C30000 */
    { 0xA7018C0Eu, 0x000234A8u },  /* A7018C0E 000234A8 */
    { 0xA7018C20u, 0x40230000u },  /* A7018C20 40230000 */
    { 0xA7018C22u, 0x00620000u },  /* A7018C22 00620000 */
    { 0xA7019798u, 0x18230004u },  /* A7019798 18230004 */
    { 0xA701979Au, 0x00629683u },  /* A701979A 00629683 */
    { 0xA70198B2u, 0xACC3ACC4u },  /* A70198B2 ACC3ACC4 */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
    { 0xA4057010u, 0x260201C0u },  /* A4057010 260201C0 */
    { 0xA704D984u, 0x37C30000u },  /* A704D984 37C30000 */
    { 0xA704D986u, 0x00069506u },  /* A704D986 00069506 */
    { 0xA704D994u, 0x30230000u },  /* A704D994 30230000 */
    { 0xA704D996u, 0x00460000u },  /* A704D996 00460000 */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
    { 0xA40244ECu, 0x800229D8u },  /* A40244EC 800229D8 */
    { 0xA701C968u, 0x48100000u },  /* A701C968 48100000 */
    { 0xA701C974u, 0x302303A4u },  /* A701C974 302303A4 */
    { 0xA701C976u, 0x00468D26u },  /* A701C976 00468D26 */
    { 0xA701C564u, 0x48100000u },  /* A701C564 48100000 */
    { 0xA701C570u, 0x302303A4u },  /* A701C570 302303A4 */
    { 0xA701C572u, 0x00468D26u },  /* A701C572 00468D26 */
    { 0xA701C808u, 0x40230000u },  /* A701C808 40230000 */
    { 0xA701C80Au, 0x00620000u },  /* A701C80A 00620000 */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
};
static const GsCheat gs_metric_units = { "Metric units", gs_metric_units_codes, sizeof(gs_metric_units_codes) / sizeof(gs_metric_units_codes[0]) };

/* [HUD & rear view mirror toggle] - Silent. Allows to toggle the rear view mirror by tapping L3 (cycling between “always on”, “default” and “always off”) and toggle the entire HUD by holding L3. */
static const GsCode gs_hud_mirror_codes[] = {
    { 0xA403EC6Cu, 0x02602021u },  /* A403EC6C 02602021 */
    { 0xD7010001u, 0x00000200u },  /* D7010001 00000200 */
    { 0xA002951Cu, 0x1040000Cu },  /* A002951C 1040000C */
    { 0x9002951Cu, 0x00000001u },  /* 9002951C 00000001 # Always on */
    { 0xA002951Cu, 0x0800A554u },  /* A002951C 0800A554 */
    { 0x9002951Cu, 0x1040000Cu },  /* 9002951C 1040000C # Default */
    { 0xA002951Cu, 0x00000000u },  /* A002951C 00000000 */
    { 0x9002951Cu, 0x0800A554u },  /* 9002951C 0800A554 # Always off */
    { 0xA002951Cu, 0x00000001u },  /* A002951C 00000001 */
    { 0x9002951Cu, 0x00000000u },  /* 9002951C 00000000 */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
    { 0xA403EC6Cu, 0x02602021u },  /* A403EC6C 02602021 */
    { 0xD701003Cu, 0x00000200u },  /* D701003C 00000200 */
    { 0xF502942Cu, 0x0022A52Eu },  /* F502942C 0022A52E */
    { 0xF502942Eu, 0x14400800u },  /* F502942E 14400800 */
    { 0xF502941Cu, 0xBA040000u },  /* F502941C BA040000 */
    { 0xF502941Eu, 0x0C000000u },  /* F502941E 0C000000 */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
};
static const GsCheat gs_hud_mirror = { "HUD & rear view mirror toggle", gs_hud_mirror_codes, sizeof(gs_hud_mirror_codes) / sizeof(gs_hud_mirror_codes[0]) };

/* [Replay cameras in race] - Silent. Makes all replay cameras accessible in race, and allows to switch the cinematic camera by holding R1. */
static const GsCode gs_replay_cams_codes[] = {
    { 0xA401F888u, 0xAEB40008u },  /* A401F888 AEB40008 */
    { 0xA701031Cu, 0x00030009u },  /* A701031C 00030009 */
    { 0xA7010370u, 0x40F045C1u },  /* A7010370 40F045C1 */
    { 0xC30A92BCu, 0x00000001u },  /* C30A92BC 0001 # Replay off */
    { 0xA701171Cu, 0x0106010Eu },  /* A701171C 0106010E */
    { 0xA7011778u, 0x45E945D7u },  /* A7011778 45E945D7 */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
    { 0xA401F888u, 0xAEB40008u },  /* A401F888 AEB40008 */
    { 0xC30A92BCu, 0x00000001u },  /* C30A92BC 0001 # Replay off */
    { 0xD701001Eu, 0x01000008u },  /* D701001E 01000008 */
    { 0xF5010148u, 0x40B6427Fu },  /* F5010148 40B6427F */
    { 0xF5010A4Cu, 0x006C8021u },  /* F5010A4C 006C8021 */
    { 0xF5010A4Eu, 0x8C700000u },  /* F5010A4E 8C700000 */
    { 0x301FFA89u, 0x00000002u },  /* 301FFA89 0002 */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
    { 0xA401F888u, 0xAEB40008u },  /* A401F888 AEB40008 */
    { 0xC40A92BCu, 0x00000000u },  /* C40A92BC 0000 */
    { 0xD001171Cu, 0x0000010Eu },  /* D001171C 010E */
    { 0x8001171Cu, 0x00000106u },  /* 8001171C 0106 */
    { 0xD0011778u, 0x000045D7u },  /* D0011778 45D7 */
    { 0x80011778u, 0x000045E9u },  /* 80011778 45E9 */
    { 0xA0010A4Cu, 0x00008021u },  /* A0010A4C 00008021 */
    { 0x90010A4Cu, 0x8C70006Cu },  /* 90010A4C 8C70006C */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
};
static const GsCheat gs_replay_cams = { "Replay cameras in race", gs_replay_cams_codes, sizeof(gs_replay_cams_codes) / sizeof(gs_replay_cams_codes[0]) };

/* [BGM Switch] - Silent. This patch allows for switching the in-race music by pressing R3. Holding R3 will mute music instead. */
static const GsCode gs_bgm_switch_codes[] = {
    { 0xD702003Cu, 0x02000400u },  /* D702003C 02000400 */
    { 0x51050005u, 0x00000001u },  /* 51050005 01 */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
    { 0x52900002u, 0x0000003Cu },  /* 52900002 0000003C */
    { 0x51050005u, 0x00000002u },  /* 51050005 02 */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
    { 0x52900002u, 0x00000000u },  /* 52900002 00000000 */
    { 0x52100005u, 0x00000001u },  /* 52100005 01 */
    { 0x51050005u, 0x00000003u },  /* 51050005 03 */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
    { 0x51050003u, 0x00000000u },  /* 51050003 00 */
    { 0xA403EC6Cu, 0x02602021u },  /* A403EC6C 02602021 */
    { 0x52130005u, 0x00000002u },  /* 52130005 02 */
    { 0x51810003u, 0x0002F4ECu },  /* 51810003 0002F4EC */
    { 0x51060304u, 0x000002EEu },  /* 51060304 000002EE */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
    { 0x52130005u, 0x00000002u },  /* 52130005 02 */
    { 0x52900003u, 0x00000000u },  /* 52900003 00000000 */
    { 0x51050005u, 0x00000000u },  /* 51050005 00 */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
    { 0x52100005u, 0x00000003u },  /* 52100005 03 */
    { 0x52150004u, 0x00000005u },  /* 52150004 05 */
    { 0x51030404u, 0x00000001u },  /* 51030404 01 */
    { 0x52120004u, 0x00000005u },  /* 52120004 05 */
    { 0x51050004u, 0x00000000u },  /* 51050004 00 */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
    { 0x52100005u, 0x00000003u },  /* 52100005 03 */
    { 0x52100004u, 0x000000FEu },  /* 52100004 FE */
    { 0x51050004u, 0x00000000u },  /* 51050004 00 */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
    { 0x52100005u, 0x00000002u },  /* 52100005 02 */
    { 0x52150004u, 0x00000005u },  /* 52150004 05 */
    { 0x51050004u, 0x000000FEu },  /* 51050004 FE */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
    { 0x52910003u, 0x00000000u },  /* 52910003 00000000 */
    { 0x51830303u, 0x000002EEu },  /* 51830303 000002EE */
    { 0x51040403u, 0x00000000u },  /* 51040403 00 */
    { 0x51050005u, 0x00000000u },  /* 51050005 00 */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
};
static const GsCheat gs_bgm_switch = { "BGM Switch", gs_bgm_switch_codes, sizeof(gs_bgm_switch_codes) / sizeof(gs_bgm_switch_codes[0]) };
