/* GENERATED by tools/cht_to_c.py - do not edit.
 * source: SCUS-94488_v1.1.cht  sha256 36d02f51ef96d1c0aa7802e40e9047f0a5e47e81042bb6e995f61b4ea3e56959
 * header: ; Gran Turismo 2 (USA) (Simulation Mode) (Rev 1) [SCUS-94488] - v1.1 cheats derived by GT2Recomp
 * Each entry is one database line, verbatim, as (first word, second word). */
#include <stdint.h>
#include "gameshark_vm.h"

/* [A Ton Of Cash] - community (DuckStation cheats.zip, v1.0/v1.2), re-derived for v1.1 by GT2Recomp. Credits held at 99,999,999 while in the GT-mode menus (the v1.0 code wrote 0x801D0FC8, dead memory on v1.1; the v1.1 credits word is 0x801D1338 = profile 0 + 0x4014). */
static const GsCode gs_v11_cash_codes[] = {
    { 0xA4017A3Cu, 0x00741823u },  /* A4017A3C 00741823 */
    { 0x901D1338u, 0x05F5E0FFu },  /* 901D1338 05F5E0FF */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
};
static const GsCheat gs_v11_cash = { "A Ton Of Cash", gs_v11_cash_codes, sizeof(gs_v11_cash_codes) / sizeof(gs_v11_cash_codes[0]) };

/* [Money Never Decreases] - community (DuckStation cheats.zip, v1.0/v1.2), re-derived for v1.1 by GT2Recomp. The two purchase paths store the reduced balance with sw v1,0x4014(sN); both stores become no-ops (the community code's 0x2400 halfword, on the same instructions at the same addresses on v1.1). Restored when the cheat is switched off. */
static const GsCode gs_v11_money_never_dec_codes[] = {
    { 0xA4017A3Cu, 0x00741823u },  /* A4017A3C 00741823 */
    { 0xA7017A42u, 0xAE232400u },  /* A7017A42 AE232400 */
    { 0xA7017D4Au, 0xAE432400u },  /* A7017D4A AE432400 */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
};
static const GsCheat gs_v11_money_never_dec = { "Money Never Decreases", gs_v11_money_never_dec_codes, sizeof(gs_v11_money_never_dec_codes) / sizeof(gs_v11_money_never_dec_codes[0]) };

/* [Any Car Can Play Any Circuit] - community (DuckStation cheats.zip, v1.0/v1.2), re-derived for v1.1 by GT2Recomp. The horsepower-limit check at 0x800148E0 (beq v0,v1,+0xC) becomes an unconditional branch, the community patch on the identical v1.1 instruction. Restored when switched off. */
static const GsCode gs_v11_any_car_codes[] = {
    { 0xA4017A3Cu, 0x00741823u },  /* A4017A3C 00741823 */
    { 0xA70148E2u, 0x10431000u },  /* A70148E2 10431000 */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
};
static const GsCheat gs_v11_any_car = { "Any Car Can Play Any Circuit", gs_v11_any_car_codes, sizeof(gs_v11_any_car_codes) / sizeof(gs_v11_any_car_codes[0]) };

/* [Have All Gold Licenses] - community (DuckStation cheats.zip, v1.0/v1.2), re-derived for v1.1 by GT2Recomp. All 60 licence tests (6 classes x 10, records of 0xA4 bytes from 0x801CAAC8 = save base + 0x1418) marked gold (halfword 0x0400). GAME STATUS shows 60 gold cups and the S badge; every test lists a gold trophy. */
static const GsCode gs_v11_gold_all_codes[] = {
    { 0xA4017A3Cu, 0x00741823u },  /* A4017A3C 00741823 */
    { 0x50003CA4u, 0x00000000u },  /* 50003CA4 0000 */
    { 0x801CAAC8u, 0x00000400u },  /* 801CAAC8 0400 */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
};
static const GsCheat gs_v11_gold_all = { "Have All Gold Licenses", gs_v11_gold_all_codes, sizeof(gs_v11_gold_all_codes) / sizeof(gs_v11_gold_all_codes[0]) };

/* [Gold Super License] - community (DuckStation cheats.zip, v1.0/v1.2), re-derived for v1.1 by GT2Recomp.  */
static const GsCode gs_v11_gold_s_codes[] = {
    { 0xA4017A3Cu, 0x00741823u },  /* A4017A3C 00741823 */
    { 0x50000AA4u, 0x00000000u },  /* 50000AA4 0000 */
    { 0x801CAAC8u, 0x00000400u },  /* 801CAAC8 0400 */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
};
static const GsCheat gs_v11_gold_s = { "Gold Super License", gs_v11_gold_s_codes, sizeof(gs_v11_gold_s_codes) / sizeof(gs_v11_gold_s_codes[0]) };

/* [Gold Licenses I-A] - community (DuckStation cheats.zip, v1.0/v1.2), re-derived for v1.1 by GT2Recomp.  */
static const GsCode gs_v11_gold_ia_codes[] = {
    { 0xA4017A3Cu, 0x00741823u },  /* A4017A3C 00741823 */
    { 0x50000AA4u, 0x00000000u },  /* 50000AA4 0000 */
    { 0x801CB130u, 0x00000400u },  /* 801CB130 0400 */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
};
static const GsCheat gs_v11_gold_ia = { "Gold Licenses I-A", gs_v11_gold_ia_codes, sizeof(gs_v11_gold_ia_codes) / sizeof(gs_v11_gold_ia_codes[0]) };

/* [Gold Licenses I-B] - community (DuckStation cheats.zip, v1.0/v1.2), re-derived for v1.1 by GT2Recomp.  */
static const GsCode gs_v11_gold_ib_codes[] = {
    { 0xA4017A3Cu, 0x00741823u },  /* A4017A3C 00741823 */
    { 0x50000AA4u, 0x00000000u },  /* 50000AA4 0000 */
    { 0x801CB798u, 0x00000400u },  /* 801CB798 0400 */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
};
static const GsCheat gs_v11_gold_ib = { "Gold Licenses I-B", gs_v11_gold_ib_codes, sizeof(gs_v11_gold_ib_codes) / sizeof(gs_v11_gold_ib_codes[0]) };

/* [Gold Licenses I-C] - community (DuckStation cheats.zip, v1.0/v1.2), re-derived for v1.1 by GT2Recomp.  */
static const GsCode gs_v11_gold_ic_codes[] = {
    { 0xA4017A3Cu, 0x00741823u },  /* A4017A3C 00741823 */
    { 0x50000AA4u, 0x00000000u },  /* 50000AA4 0000 */
    { 0x801CBE00u, 0x00000400u },  /* 801CBE00 0400 */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
};
static const GsCheat gs_v11_gold_ic = { "Gold Licenses I-C", gs_v11_gold_ic_codes, sizeof(gs_v11_gold_ic_codes) / sizeof(gs_v11_gold_ic_codes[0]) };

/* [Gold Licenses A] - community (DuckStation cheats.zip, v1.0/v1.2), re-derived for v1.1 by GT2Recomp.  */
static const GsCode gs_v11_gold_a_codes[] = {
    { 0xA4017A3Cu, 0x00741823u },  /* A4017A3C 00741823 */
    { 0x50000AA4u, 0x00000000u },  /* 50000AA4 0000 */
    { 0x801CC468u, 0x00000400u },  /* 801CC468 0400 */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
};
static const GsCheat gs_v11_gold_a = { "Gold Licenses A", gs_v11_gold_a_codes, sizeof(gs_v11_gold_a_codes) / sizeof(gs_v11_gold_a_codes[0]) };

/* [Gold Licenses B] - community (DuckStation cheats.zip, v1.0/v1.2), re-derived for v1.1 by GT2Recomp.  */
static const GsCode gs_v11_gold_b_codes[] = {
    { 0xA4017A3Cu, 0x00741823u },  /* A4017A3C 00741823 */
    { 0x50000AA4u, 0x00000000u },  /* 50000AA4 0000 */
    { 0x801CCAD0u, 0x00000400u },  /* 801CCAD0 0400 */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
};
static const GsCheat gs_v11_gold_b = { "Gold Licenses B", gs_v11_gold_b_codes, sizeof(gs_v11_gold_b_codes) / sizeof(gs_v11_gold_b_codes[0]) };

/* [All Races Completed] - community (DuckStation cheats.zip, v1.0/v1.2), re-derived for v1.1 by GT2Recomp. The race-completion flag array (68 halfwords from 0x801C97C8 = save base + 0x118) filled with 0x1111, as the community code did on v1.0. GAME STATUS then reports the game complete (over 100%, as that code always did); the Arcade disc reads the same save to unlock its Simulation credits. */
static const GsCode gs_v11_races_done_codes[] = {
    { 0xA4017A3Cu, 0x00741823u },  /* A4017A3C 00741823 */
    { 0x50004402u, 0x00000000u },  /* 50004402 0000 */
    { 0x801C97C8u, 0x00001111u },  /* 801C97C8 1111 */
    { 0x00000000u, 0x0000FFFFu },  /* 00000000 FFFF */
};
static const GsCheat gs_v11_races_done = { "All Races Completed", gs_v11_races_done_codes, sizeof(gs_v11_races_done_codes) / sizeof(gs_v11_races_done_codes[0]) };
