#!/usr/bin/env python3
"""Turn sections of a DuckStation .cht patch file into C tables for gameshark_vm.

    cht_to_c.py <out.h> <file.cht> <section>=<c_ident> [<section>=<c_ident> ...]

Every code line is copied VERBATIM (as data) and echoed in a comment beside
its C form, so a reviewer can diff the table against the database by eye.
Sections whose codes use an opcode the VM does not implement are refused
here, at build time, rather than at a player's VBlank.
"""
import re, sys, hashlib, os

# Opcodes gameshark_vm.c implements. Keep in sync with the switch there.
IMPLEMENTED = {
    0x00, 0x30, 0x31, 0x32, 0x80, 0x81, 0x82, 0x90, 0x91, 0x92,
    0x10, 0x11, 0x20, 0x21, 0x60, 0x61,
    0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8,
    0xC0, 0xC3, 0xC4, 0xC5, 0xC6,
    0xD0, 0xD1, 0xD2, 0xD3, 0xD7,
    0xE0, 0xE1, 0xE2, 0xE3,
    0xF5, 0x1F, 0x50,
    0x51, 0x52,
}
REG51_OK = {0x00,0x01,0x02,0x03,0x04,0x05,0x06, 0x40,0x41,0x42,0x43,0x44,0x45,0x46,
            0x80,0x81,0x82,0x83,0x84,0x85,0x86, 0xC0,0xC1,0xC2,0xC3,0xC4,0xC5,0xC6,0xC7,0xC8,0xC9,0xCA,
            0xD0,0xD1,0xD2}

def parse(path):
    text = open(path, encoding="utf-8").read()
    header = text.splitlines()[0] if text else ""
    secs = {}
    cur = None
    for line in text.splitlines():
        m = re.match(r"^\[(.+?)\]\s*$", line)
        if m:
            cur = m.group(1).strip(); secs[cur] = {"meta": {}, "codes": [], "raw": []}
            continue
        if cur is None: continue
        s = line.strip()
        if not s: continue
        secs[cur]["raw"].append(line)
        if s.startswith("#") or s.startswith(";"): continue
        m = re.match(r"^([0-9A-Fa-f]{8})\s+([0-9A-Fa-f]{2,8})(\s*#.*)?$", s)
        if m:
            a = int(m.group(1), 16); v = int(m.group(2), 16)
            secs[cur]["codes"].append((a, v, len(m.group(2)), line))
            continue
        m = re.match(r"^([A-Za-z0-9_ ]+?)\s*=\s*(.*)$", s)
        if m: secs[cur]["meta"][m.group(1).strip()] = m.group(2).strip()
    return header, secs

def check(name, codes):
    for a, v, w, line in codes:
        op = a >> 24
        if op not in IMPLEMENTED:
            sys.exit(f"{name}: opcode {op:02X} not implemented by gameshark_vm ({line.strip()})")
        if op == 0x51 and ((a >> 16) & 0xFF) not in REG51_OK:
            sys.exit(f"{name}: 51 sub-op {(a>>16)&0xFF:02X} not implemented ({line.strip()})")
        if op == 0x52:
            hi = (a >> 20) & 0xF; lo = (a >> 16) & 0xF
            if hi not in (0,1,2,3,4,5,6,7,8,9,0xA,0xB) or lo not in range(0,12):
                sys.exit(f"{name}: 52 sub-op {(a>>16)&0xFF:02X} not implemented ({line.strip()})")

def main():
    out, cht = sys.argv[1], sys.argv[2]
    wanted = [w.split("=", 1) for w in sys.argv[3:]]
    header, secs = parse(cht)
    sha = hashlib.sha256(open(cht, "rb").read()).hexdigest()
    lines = []
    lines.append("/* GENERATED by tools/cht_to_c.py - do not edit.")
    lines.append(f" * source: {os.path.basename(cht)}  sha256 {sha}")
    lines.append(f" * header: {header.lstrip('# ').strip()}")
    lines.append(" * Each entry is one database line, verbatim, as (first word, second word). */")
    lines.append("#include <stdint.h>")
    lines.append('#include "gameshark_vm.h"')
    for sec, ident in wanted:
        if sec not in secs: sys.exit(f"section [{sec}] not in {cht}; have: {list(secs)}")
        codes = secs[sec]["codes"]; meta = secs[sec]["meta"]
        check(sec, codes)
        lines.append("")
        lines.append(f"/* [{sec}] - {meta.get('Author','?')}. {meta.get('Description','')} */")
        lines.append(f"static const GsCode {ident}_codes[] = {{")
        for a, v, w, line in codes:
            lines.append(f"    {{ 0x{a:08X}u, 0x{v:08X}u }},  /* {line.strip()} */")
        lines.append("};")
        lines.append(f"static const GsCheat {ident} = {{ \"{sec}\", {ident}_codes, "
                     f"sizeof({ident}_codes) / sizeof({ident}_codes[0]) }};")
    open(out, "w", encoding="utf-8").write("\n".join(lines) + "\n")
    print(f"wrote {out}: {len(wanted)} sections")

if __name__ == "__main__":
    main()
